<!-- navbar css file link  -->
<link rel="stylesheet" href="<?php echo $css;?>navbar.css">

</head>
<body>
    <nav class="my-navbar">
       <div class="logo">
            <i class="fas fa-futbol"></i>
            <span>sy-koora</span>
       </div>
       <ul class="list">
           <li><a href="index.php">home page</a></li>
           <li><a href="leagues.php">leagues</a></li>
           <li><a href="teams.php">teams</a></li>
           <li><a href="matches.php">matches</a></li>
           <li><a href="news.php">news</a></li>
       </ul>
    </nav>